events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
       
        root /var/www/public;
        index index.php index.html;

        # ✅ Swagger UI Static Assets (WICHTIG: Vor API Docs!)
        location ~ ^/bundles/nelmioapidoc/ {
            alias /var/www/public/bundles/nelmioapidoc/;
            try_files $uri =404;
            add_header Cache-Control "public, max-age=31536000";
            
        }

        # Swagger API Docs UI
        location /api/doc {
            try_files $uri /index.php$is_args$args;
        }

        # Normaler Frontend / Symfony-Fallback
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }
        location ^~ /swagger-ui/ {
            alias /var/www/public/bundles/nelmioapidoc/swagger-ui/;
            try_files $uri =404;
            access_log off;
            add_header Cache-Control "public, max-age=31536000";
        }
        # PHP-FPM
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass agent_host:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
        }
    }
}